(function () {
  "use strict";

  const DB = globalThis.FamilyTreeDB;
  const Gedcom = globalThis.FamilyTreeGedcom;
  const state = { data: null, pendingAttachments: [], editingSourceId: "", selectedPersonId: "", selectedRelationshipId: "", parsedGedcom: null, showAllSnapshots: false, undoTimer: 0 };
  const el = {};
  const SOURCE_TYPES = [
    ["family-register", "戸籍・除籍"], ["certificate", "証明書"], ["photograph", "写真"], ["interview", "聞き取り"], ["letter", "手紙"], ["diary", "日記"], ["gravestone", "墓碑"], ["newspaper", "新聞"], ["book", "書籍"], ["website", "Webサイト"], ["personal-memory", "本人・家族の記憶"], ["other", "その他"]
  ];
  const EVENT_TYPES = [["birth", "出生"], ["death", "死亡"], ["marriage", "結婚"], ["divorce", "離婚"], ["adoption", "養子縁組"], ["residence", "居住"], ["education", "学歴"], ["occupation", "職歴"], ["military", "兵役"], ["immigration", "移住"], ["illness", "病歴"], ["award", "受賞"], ["burial", "埋葬"], ["custom", "その他"]];
  const VERIFY_LABELS = { confirmed: "確認済み", probable: "可能性が高い", unconfirmed: "未確認", disputed: "情報が食い違っている" };
  const RELIABILITY_LABELS = { high: "信頼性が高い", medium: "参考情報", low: "未確認", unknown: "不明" };

  function cache() { document.querySelectorAll("[id]").forEach(function (node) { el[node.id] = node; }); }
  function escapeHtml(value) { return String(value === null || value === undefined ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
  function fullName(person) { return person ? ((person.familyName || "") + " " + (person.givenName || "")).trim() || "名前未設定" : "不明な人物"; }
  function personById(id) { return state.data && state.data.persons.find(function (person) { return person.id === id; }); }
  function sourceById(id) { return state.data && state.data.sources.find(function (source) { return source.id === id; }); }
  function readable(error, fallback) { return error && error.message || fallback || "処理に失敗しました。"; }
  function showMessage(message, error) { const node = document.createElement("div"); node.className = "toast" + (error ? " is-error" : ""); node.textContent = message; el.toastRegion.appendChild(node); setTimeout(function () { node.remove(); }, error ? 5200 : 3400); }
  function setBusy(button, busy, text) { if (!button) return; if (busy) { button.dataset.label = button.textContent; button.textContent = text || "処理中…"; button.disabled = true; } else { button.textContent = button.dataset.label || button.textContent; button.disabled = false; delete button.dataset.label; } }
  function formatBytes(bytes) { const value = Number(bytes || 0); if (value < 1024) return value + "B"; if (value < 1024 * 1024) return Math.round(value / 1024) + "KB"; return (value / 1024 / 1024).toFixed(1) + "MB"; }
  function formatPartialDate(value, precision, approximate) { if (!value || precision === "unknown") return "時期不明"; const parts = value.split("-").map(Number); let text = parts[0] + "年"; if (precision === "month" || precision === "day") text += parts[1] + "月"; if (precision === "day") text += parts[2] + "日"; return text + (approximate ? "頃" : ""); }
  function closeSettings() { if (el.settingsDialog && el.settingsDialog.open) el.settingsDialog.close(); }
  function optionHtml(items) { return items.map(function (item) { return "<option value=\"" + item[0] + "\">" + item[1] + "</option>"; }).join(""); }
  function debounce(fn, wait) { let timer; return function () { const args = arguments; clearTimeout(timer); timer = setTimeout(function () { fn.apply(null, args); }, wait || 180); }; }

  async function refresh() {
    state.data = await DB.readAll();
    el.currentTreeName.textContent = state.data.currentTree ? state.data.currentTree.name : "家系図";
    el.currentTreeName.title = state.data.currentTree ? state.data.currentTree.name : "";
    renderTreeManager(); renderTimelineFilters(); renderTimeline(); renderSourceFilters(); renderSources(); await renderStatistics();
    if (el.settingsDialog) el.settingsDialog.querySelector(".dialog-header h2").textContent = "設定・データ管理 — " + (state.data.currentTree ? state.data.currentTree.name : "");
  }

  function switchView(view) {
    [el.treeSection, el.peopleSection, el.timelineSection, el.sourcesSection, el.statisticsSection].forEach(function (section) { if (section) section.hidden = true; });
    if (view === "tree") el.treeSection.hidden = false;
    else if (view === "people") el.peopleSection.hidden = false;
    else if (view === "timeline") { el.timelineSection.hidden = false; refresh().catch(function (error) { showMessage(readable(error), true); }); }
    else if (view === "sources") { el.sourcesSection.hidden = false; refresh().catch(function (error) { showMessage(readable(error), true); }); }
    else if (view === "statistics") { el.statisticsSection.hidden = false; refresh().catch(function (error) { showMessage(readable(error), true); }); }
    document.querySelectorAll("[data-app-view],[data-v4-view]").forEach(function (button) { button.classList.toggle("is-active", button.dataset.appView === view || button.dataset.v4View === view); });
  }

  function renderTreeManager() {
    if (!state.data) return;
    const showArchived = el.showArchivedTrees.checked;
    const trees = state.data.trees.filter(function (tree) { return showArchived || !tree.isArchived; });
    el.treeManagerList.innerHTML = trees.map(function (tree) {
      const current = tree.id === state.data.currentTree.id;
      return "<article class=\"tree-manager-card" + (current ? " is-current" : "") + (tree.isArchived ? " is-archived" : "") + "\" style=\"--tree-color:" + escapeHtml(tree.coverColor) + "\"><div class=\"tree-color\"></div><div class=\"tree-manager-main\"><strong title=\"" + escapeHtml(tree.name) + "\">" + escapeHtml(tree.name) + "</strong><p>" + escapeHtml(tree.description || "説明なし") + "</p><small>" + (current ? "現在表示中・" : "") + (tree.isArchived ? "アーカイブ" : "利用中") + "</small></div><div class=\"tree-manager-actions\">" + (!current ? "<button type=\"button\" data-tree-action=\"switch\" data-tree-id=\"" + tree.id + "\">切り替え</button>" : "") + "<button type=\"button\" data-tree-action=\"edit\" data-tree-id=\"" + tree.id + "\">編集</button><button type=\"button\" data-tree-action=\"duplicate\" data-tree-id=\"" + tree.id + "\">複製</button><button type=\"button\" data-tree-action=\"archive\" data-tree-id=\"" + tree.id + "\">" + (tree.isArchived ? "解除" : "保管") + "</button><button class=\"danger-text\" type=\"button\" data-tree-action=\"delete\" data-tree-id=\"" + tree.id + "\">削除</button></div></article>";
    }).join("") || "<p class=\"review-empty\">表示する家系図がありません。</p>";
  }

  function openTreeForm(tree) { el.treeForm.reset(); el.treeId.value = tree ? tree.id : ""; el.treeName.value = tree ? tree.name : ""; el.treeDescription.value = tree ? tree.description : ""; el.treeCoverColor.value = tree && tree.coverColor || "#557c64"; el.treeFormTitle.textContent = tree ? "家系図を編集" : "家系図を作成"; el.treeFormError.hidden = true; el.treeFormDialog.showModal(); }
  async function saveTree(event) { event.preventDefault(); el.treeFormError.hidden = true; try { const input = { id: el.treeId.value, name: el.treeName.value, description: el.treeDescription.value, coverColor: el.treeCoverColor.value }; if (input.id) await DB.updateTree(input); else await DB.createTree(input); el.treeFormDialog.close(); location.reload(); } catch (error) { el.treeFormError.textContent = readable(error); el.treeFormError.hidden = false; } }
  async function treeAction(event) {
    const button = event.target.closest("[data-tree-action]"); if (!button) return; const tree = state.data.trees.find(function (item) { return item.id === button.dataset.treeId; }); if (!tree) return;
    try {
      if (button.dataset.treeAction === "switch") { await DB.switchTree(tree.id); location.reload(); }
      else if (button.dataset.treeAction === "edit") openTreeForm(tree);
      else if (button.dataset.treeAction === "duplicate") { if (!confirm("「" + tree.name + "」を人物・資料・添付を含めて複製しますか？")) return; setBusy(button, true, "複製中…"); await DB.duplicateTree(tree.id); location.reload(); }
      else if (button.dataset.treeAction === "archive") { await DB.setTreeArchived(tree.id, !tree.isArchived); await refresh(); }
      else if (button.dataset.treeAction === "delete") { const typed = prompt("家系図内の人物・関係・出来事・資料・添付を削除します。\n確認のため家系図名「" + tree.name + "」を入力してください。", ""); if (typed !== tree.name) { if (typed !== null) showMessage("家系図名が一致しないため削除しませんでした。", true); return; } await DB.deleteTree(tree.id); location.reload(); }
    } catch (error) { setBusy(button, false); showMessage(readable(error), true); }
  }

  function renderTimelineFilters() {
    const currentPerson = el.timelinePersonFilter.value; el.timelinePersonFilter.innerHTML = "<option value=\"all\">全員</option>" + state.data.persons.slice().sort(function (a, b) { return fullName(a).localeCompare(fullName(b), "ja"); }).map(function (person) { return "<option value=\"" + person.id + "\">" + escapeHtml(fullName(person)) + "</option>"; }).join(""); if (Array.from(el.timelinePersonFilter.options).some(function (option) { return option.value === currentPerson; })) el.timelinePersonFilter.value = currentPerson;
    if (el.timelineTypeFilter.options.length === 1) el.timelineTypeFilter.insertAdjacentHTML("beforeend", optionHtml(EVENT_TYPES));
  }
  function eventIssue(event) { const today = new Date().toISOString().slice(0, 10); if (event.date && event.date > today) return "未来の日付"; const people = (event.personIds || []).map(personById).filter(Boolean); const afterDeath = people.find(function (person) { return person.deathDate && event.date && event.date > person.deathDate; }); return afterDeath ? "没年月日後の出来事" : ""; }
  function ageAtEvent(event, person) { if (!event.date || !person || !person.birthDate) return ""; const eventYear = Number(event.date.slice(0, 4)); const birthYear = Number(person.birthDate.slice(0, 4)); if (!eventYear || !birthYear || eventYear < birthYear) return ""; const approx = event.datePrecision !== "day" || person.birthDatePrecision !== "day"; return (approx ? "約" : "") + (eventYear - birthYear) + "歳"; }
  function eventCard(event, personContext) {
    const people = (event.personIds || []).map(personById).filter(Boolean); const primary = personContext || people[0]; const cited = state.data.citations.some(function (citation) { return citation.targetType === "event" && citation.targetId === event.id; }); const issue = eventIssue(event);
    return "<article class=\"timeline-card" + (issue ? " has-issue" : "") + "\"><div class=\"timeline-date\"><strong>" + escapeHtml(formatPartialDate(event.date, event.datePrecision, event.dateApproximate)) + "</strong><small>" + escapeHtml(ageAtEvent(event, primary)) + "</small></div><div class=\"timeline-content\"><div class=\"timeline-title\"><strong>" + escapeHtml(event.title) + "</strong><span>" + escapeHtml(EVENT_TYPES.find(function (item) { return item[0] === event.eventType; })?.[1] || "その他") + "</span></div><p>" + escapeHtml(people.map(fullName).join("・")) + (event.place ? "／" + escapeHtml(event.place) : "") + "</p><small class=\"verification-chip is-" + event.verificationStatus + "\">" + escapeHtml(VERIFY_LABELS[event.verificationStatus] || "未確認") + "</small>" + (cited ? "<small class=\"citation-chip\">▤ 出典あり</small>" : "") + (event.isSensitive ? "<small class=\"sensitive-chip\">鍵 要配慮</small>" : "") + (issue ? "<small class=\"issue-chip\">" + issue + "</small>" : "") + "</div><div class=\"timeline-actions\"><button type=\"button\" data-event-action=\"edit\" data-event-id=\"" + event.id + "\">編集</button><button type=\"button\" data-event-action=\"cite\" data-event-id=\"" + event.id + "\">出典</button><button class=\"danger-text\" type=\"button\" data-event-action=\"delete\" data-event-id=\"" + event.id + "\">削除</button></div></article>";
  }
  function renderTimeline() {
    if (!state.data) return; const personId = el.timelinePersonFilter.value; const type = el.timelineTypeFilter.value; const verification = el.timelineVerificationFilter.value; const decade = Number(el.timelineDecadeFilter.value); const citedIds = new Set(state.data.citations.filter(function (item) { return item.targetType === "event"; }).map(function (item) { return item.targetId; }));
    const events = state.data.events.filter(function (event) { if (personId !== "all" && !(event.personIds || []).includes(personId)) return false; if (type !== "all" && event.eventType !== type) return false; if (verification !== "all" && event.verificationStatus !== verification) return false; if (decade && (!event.date || Number(event.date.slice(0, 4)) < decade || Number(event.date.slice(0, 4)) >= decade + 10)) return false; if (el.timelineCitedOnly.checked && !citedIds.has(event.id)) return false; return true; }).sort(function (a, b) { return (a.date || "9999").localeCompare(b.date || "9999") || (a.sortOrder || 0) - (b.sortOrder || 0); });
    el.timelineCount.textContent = events.length + "件"; const groups = new Map(); events.forEach(function (event) { const year = event.date ? event.date.slice(0, 4) : "時期不明"; if (!groups.has(year)) groups.set(year, []); groups.get(year).push(event); }); el.timelineList.innerHTML = Array.from(groups).map(function (entry) { return "<section class=\"timeline-year\"><h3>" + escapeHtml(entry[0]) + (entry[0] === "時期不明" ? "" : "年") + "</h3>" + entry[1].map(function (event) { return eventCard(event); }).join("") + "</section>"; }).join("") || "<div class=\"review-empty\"><strong>該当する出来事はありません</strong><p>「出来事を追加」から人物の記録を作成できます。</p></div>";
  }
  function openEvent(event, personId) { el.eventForm.reset(); el.eventId.value = event ? event.id : ""; el.eventDialogTitle.textContent = event ? "出来事を編集" : "出来事を追加"; el.eventPersonIds.innerHTML = state.data.persons.map(function (person) { const selected = event ? (event.personIds || []).includes(person.id) : person.id === personId; return "<option value=\"" + person.id + "\"" + (selected ? " selected" : "") + ">" + escapeHtml(fullName(person)) + "</option>"; }).join(""); el.eventType.innerHTML = optionHtml(EVENT_TYPES); el.eventSourceIds.innerHTML = state.data.sources.map(function (source) { const selected = event && (event.sourceIds || []).includes(source.id); return "<option value=\"" + source.id + "\"" + (selected ? " selected" : "") + ">" + escapeHtml(source.title) + "</option>"; }).join(""); el.eventType.value = event ? event.eventType : "custom"; el.eventTitle.value = event ? event.title : ""; el.eventDatePrecision.value = event ? event.datePrecision : "unknown"; el.eventDate.value = event ? event.date : ""; el.eventDateApproximate.checked = Boolean(event && event.dateApproximate); el.eventEndDate.value = event ? event.endDate : ""; el.eventPlace.value = event ? event.place : ""; el.eventVerificationStatus.value = event ? event.verificationStatus : "unconfirmed"; el.eventSensitive.checked = Boolean(event && event.isSensitive); el.eventDescription.value = event ? event.description : ""; el.eventFormError.hidden = true; el.eventDialog.showModal(); }
  async function saveEvent(event) { event.preventDefault(); el.eventFormError.hidden = true; try { const personIds = Array.from(el.eventPersonIds.selectedOptions).map(function (option) { return option.value; }); const sourceIds = Array.from(el.eventSourceIds.selectedOptions).map(function (option) { return option.value; }); await DB.saveEvent({ id: el.eventId.value, personIds: personIds, eventType: el.eventType.value, title: el.eventTitle.value, date: el.eventDate.value, datePrecision: el.eventDatePrecision.value, dateApproximate: el.eventDateApproximate.checked, endDate: el.eventEndDate.value, place: el.eventPlace.value, verificationStatus: el.eventVerificationStatus.value, sourceIds: sourceIds, isSensitive: el.eventSensitive.checked, description: el.eventDescription.value }); el.eventDialog.close(); await refresh(); showMessage("出来事を保存しました。"); } catch (error) { el.eventFormError.textContent = readable(error); el.eventFormError.hidden = false; } }
  async function eventAction(event) { const button = event.target.closest("[data-event-action]"); if (!button) return; const item = state.data.events.find(function (value) { return value.id === button.dataset.eventId; }); if (!item) return; if (button.dataset.eventAction === "edit") openEvent(item); else if (button.dataset.eventAction === "cite") openCitation("event", item.id, "other"); else if (button.dataset.eventAction === "delete" && confirm("「" + item.title + "」を削除しますか？元に戻す操作を利用できます。")) { await DB.deleteEvent(item.id); await refresh(); } }

  function renderSourceFilters() { if (el.sourceTypeFilter.options.length === 1) el.sourceTypeFilter.insertAdjacentHTML("beforeend", optionHtml(SOURCE_TYPES)); if (el.sourceType.options.length === 0) el.sourceType.innerHTML = optionHtml(SOURCE_TYPES); }
  async function sourceAttachmentSummary(source) { const attachments = await DB.listAttachments(source.id); return { count: attachments.length, bytes: attachments.reduce(function (sum, item) { return sum + Number(item.size || 0); }, 0) }; }
  function renderSources() {
    if (!state.data) return; const query = DB.normalizeSearchText(el.sourceSearch.value); const type = el.sourceTypeFilter.value; const reliability = el.sourceReliabilityFilter.value; const sort = el.sourceSort.value; const citedCounts = new Map(); state.data.citations.forEach(function (citation) { citedCounts.set(citation.sourceId, (citedCounts.get(citation.sourceId) || 0) + 1); }); const sources = state.data.sources.filter(function (source) { const text = DB.normalizeSearchText([source.title, source.author, source.publisher, source.repository, source.referenceNumber, source.note].join(" ")); return (!query || text.includes(query)) && (type === "all" || source.sourceType === type) && (reliability === "all" || source.reliability === reliability); }).sort(function (a, b) { if (sort === "name") return a.title.localeCompare(b.title, "ja"); if (sort === "obtained") return (b.obtainedDate || "").localeCompare(a.obtainedDate || ""); return (b.updatedAt || "").localeCompare(a.updatedAt || ""); }); el.sourceCount.textContent = sources.length + "件"; el.sourceList.innerHTML = sources.map(function (source) { const typeLabel = SOURCE_TYPES.find(function (item) { return item[0] === source.sourceType; })?.[1] || "その他"; return "<article class=\"source-card\"><div class=\"source-icon\" aria-hidden=\"true\">" + (source.sourceType === "photograph" ? "写" : "資") + "</div><div class=\"source-main\"><div><strong>" + escapeHtml(source.title) + "</strong><span class=\"source-type-chip\">" + typeLabel + "</span></div><p>" + escapeHtml([source.author, source.repository, source.referenceNumber].filter(Boolean).join("／") || "詳細未登録") + "</p><small>" + escapeHtml(RELIABILITY_LABELS[source.reliability] || "不明") + "・引用 " + (citedCounts.get(source.id) || 0) + "件</small></div><div class=\"source-actions\"><button type=\"button\" data-source-action=\"edit\" data-source-id=\"" + source.id + "\">詳細・添付</button><button class=\"danger-text\" type=\"button\" data-source-action=\"delete\" data-source-id=\"" + source.id + "\">削除</button></div></article>"; }).join("") || "<div class=\"review-empty\"><strong>資料はまだありません</strong><p>戸籍、写真、聞き取りなどを登録できます。</p></div>";
  }
  async function thumbnailFor(file, lighten) {
    if (!file.type.startsWith("image/")) return { blob: file, thumbnail: "" };
    let image; let objectUrl = "";
    try {
      if (typeof createImageBitmap === "function") image = await createImageBitmap(file, { imageOrientation: "from-image" });
      else {
        objectUrl = URL.createObjectURL(file);
        image = await new Promise(function (resolve, reject) {
          const element = new Image(); element.onload = function () { resolve(element); }; element.onerror = function () { reject(new Error("画像を読み込めませんでした。")); }; element.src = objectUrl;
        });
      }
      const width = image.width || image.naturalWidth; const height = image.height || image.naturalHeight;
      if (!width || !height) throw new Error("画像サイズを確認できませんでした。");
      let blob = file;
      if (lighten && Math.max(width, height) > 2200) {
        const scale = 2200 / Math.max(width, height); const canvas = document.createElement("canvas");
        canvas.width = Math.round(width * scale); canvas.height = Math.round(height * scale); canvas.getContext("2d").drawImage(image, 0, 0, canvas.width, canvas.height);
        blob = await new Promise(function (resolve, reject) { canvas.toBlob(function (value) { value ? resolve(value) : reject(new Error("画像を軽量化できませんでした。")); }, file.type === "image/png" ? "image/webp" : "image/jpeg", .88); });
      }
      const thumbScale = Math.min(1, 320 / Math.max(width, height)); const thumb = document.createElement("canvas");
      thumb.width = Math.max(1, Math.round(width * thumbScale)); thumb.height = Math.max(1, Math.round(height * thumbScale)); thumb.getContext("2d").drawImage(image, 0, 0, thumb.width, thumb.height);
      return { blob: blob, thumbnail: thumb.toDataURL("image/webp", .78) };
    } finally { if (image && image.close) image.close(); if (objectUrl) URL.revokeObjectURL(objectUrl); }
  }
  function renderPendingAttachments() { el.pendingAttachmentList.innerHTML = state.pendingAttachments.map(function (item, index) { return "<div class=\"attachment-row\"><span class=\"attachment-thumb\">" + (item.file.type === "application/pdf" ? "PDF" : "画像") + "</span><span><strong>" + escapeHtml(item.file.name) + "</strong><small>" + formatBytes(item.file.size) + (item.file.size > 10 * 1024 * 1024 ? "・大容量" : "") + "</small></span><button type=\"button\" data-remove-pending=\"" + index + "\">外す</button></div>"; }).join(""); }
  async function renderStoredAttachments(sourceId) { if (!sourceId) { el.storedAttachmentList.innerHTML = ""; return; } const items = await DB.listAttachments(sourceId); el.storedAttachmentList.innerHTML = items.map(function (item) { return "<div class=\"attachment-row\"><span class=\"attachment-thumb\">" + (item.thumbnail ? "<img src=\"" + escapeHtml(item.thumbnail) + "\" alt=\"\">" : item.mimeType === "application/pdf" ? "PDF" : "画像") + "</span><span><strong>" + escapeHtml(item.fileName) + "</strong><small>" + formatBytes(item.size) + "</small></span><div><button type=\"button\" data-attachment-action=\"open\" data-attachment-id=\"" + item.id + "\">開く</button><button type=\"button\" data-attachment-action=\"save\" data-attachment-id=\"" + item.id + "\">保存</button><button class=\"danger-text\" type=\"button\" data-attachment-action=\"delete\" data-attachment-id=\"" + item.id + "\">削除</button></div></div>"; }).join(""); }
  async function openSource(source) { state.editingSourceId = source ? source.id : ""; state.pendingAttachments = []; el.sourceForm.reset(); el.sourceId.value = source ? source.id : ""; el.sourceDialogTitle.textContent = source ? "資料を編集" : "資料を追加"; ["Title", "Author", "Publisher", "IssuedDate", "ObtainedDate", "Repository", "ReferenceNumber", "Url", "Note"].forEach(function (suffix) { const key = suffix.charAt(0).toLowerCase() + suffix.slice(1); el["source" + suffix].value = source ? source[key] || "" : ""; }); el.sourceType.value = source ? source.sourceType : "family-register"; el.sourceReliability.value = source ? source.reliability : "unknown"; el.sourceFormError.hidden = true; renderPendingAttachments(); await renderStoredAttachments(state.editingSourceId); el.sourceDialog.showModal(); }
  async function saveSource(event) { event.preventDefault(); setBusy(el.saveSourceButton, true, "保存中…"); el.sourceFormError.hidden = true; try { const source = await DB.saveSource({ id: el.sourceId.value, title: el.sourceTitle.value, sourceType: el.sourceType.value, author: el.sourceAuthor.value, publisher: el.sourcePublisher.value, issuedDate: el.sourceIssuedDate.value, obtainedDate: el.sourceObtainedDate.value, repository: el.sourceRepository.value, referenceNumber: el.sourceReferenceNumber.value, url: el.sourceUrl.value, note: el.sourceNote.value, reliability: el.sourceReliability.value }); for (const pending of state.pendingAttachments) { const converted = await thumbnailFor(pending.file, el.lightenAttachment.checked); await DB.saveAttachment({ sourceId: source.id, fileName: pending.file.name, mimeType: converted.blob.type || pending.file.type, blob: converted.blob, thumbnail: converted.thumbnail }); } state.pendingAttachments = []; el.sourceDialog.close(); await refresh(); showMessage("資料と添付ファイルを保存しました。"); } catch (error) { el.sourceFormError.textContent = readable(error); el.sourceFormError.hidden = false; } finally { setBusy(el.saveSourceButton, false); } }
  async function sourceAction(event) { const button = event.target.closest("[data-source-action]"); if (!button) return; const source = sourceById(button.dataset.sourceId); if (!source) return; if (button.dataset.sourceAction === "edit") await openSource(source); else if (button.dataset.sourceAction === "delete") { const citationCount = state.data.citations.filter(function (item) { return item.sourceId === source.id; }).length; const attachments = await DB.listAttachments(source.id); if (!confirm("「" + source.title + "」を削除しますか？\n引用 " + citationCount + "件、添付 " + attachments.length + "件も解除・削除されます。")) return; await DB.deleteSource(source.id); await refresh(); } }
  async function attachmentAction(event) { const button = event.target.closest("[data-attachment-action]"); if (!button) return; const item = await DB.getAttachment(button.dataset.attachmentId); if (!item) return; if (button.dataset.attachmentAction === "delete") { if (confirm(item.fileName + "を削除しますか？")) { await DB.deleteAttachment(item.id); await renderStoredAttachments(state.editingSourceId); } return; } const url = URL.createObjectURL(item.blob); const link = document.createElement("a"); link.href = url; if (button.dataset.attachmentAction === "save") link.download = item.fileName; else link.target = "_blank"; link.rel = "noopener"; document.body.appendChild(link); link.click(); link.remove(); setTimeout(function () { URL.revokeObjectURL(url); }, 5000); }

  function openCitation(targetType, targetId, fieldName) { if (!state.data.sources.length) { showMessage("先に資料を登録してください。", true); switchView("sources"); return; } el.citationForm.reset(); el.citationId.value = ""; el.citationTargetType.value = targetType; el.citationTargetId.value = targetId; el.citationExistingList.innerHTML = citationRows(targetType, targetId); el.citationSourceId.innerHTML = state.data.sources.map(function (source) { return "<option value=\"" + source.id + "\">" + escapeHtml(source.title) + "</option>"; }).join(""); el.citationFieldName.value = fieldName || "other"; el.citationVerificationStatus.value = "unconfirmed"; el.citationFormError.hidden = true; el.citationDialog.showModal(); }
  async function saveCitation(event) { event.preventDefault(); el.citationFormError.hidden = true; try { await DB.saveCitation({ id: el.citationId.value, sourceId: el.citationSourceId.value, targetType: el.citationTargetType.value, targetId: el.citationTargetId.value, fieldName: el.citationFieldName.value, verificationStatus: el.citationVerificationStatus.value, page: el.citationPage.value, quotedText: el.citationQuotedText.value, note: el.citationNote.value }); el.citationDialog.close(); await refresh(); if (el.personTimelineDialog.open) await openPersonTimeline(state.selectedPersonId); showMessage("資料を引用しました。"); } catch (error) { el.citationFormError.textContent = readable(error); el.citationFormError.hidden = false; } }
  function citationRows(targetType, targetId) { const rows = state.data.citations.filter(function (citation) { return citation.targetType === targetType && citation.targetId === targetId; }); return rows.map(function (citation) { const source = sourceById(citation.sourceId); return "<div class=\"citation-row\"><span>▤</span><span><strong>" + escapeHtml(source ? source.title : "削除済み資料") + "</strong><small>" + escapeHtml(citation.fieldName) + (citation.page ? "・" + escapeHtml(citation.page) : "") + "・" + escapeHtml(VERIFY_LABELS[citation.verificationStatus] || "未確認") + "</small></span><button class=\"danger-text\" type=\"button\" data-delete-citation=\"" + citation.id + "\">引用解除</button></div>"; }).join("") || "<p class=\"empty-relative\">引用資料はありません</p>"; }

  async function openPersonTimeline(personId) { await refresh(); const person = personById(personId); if (!person) return; state.selectedPersonId = person.id; el.personTimelineTitle.textContent = fullName(person) + "の年表"; el.personTimelineList.innerHTML = state.data.events.filter(function (event) { return (event.personIds || []).includes(person.id); }).sort(function (a, b) { return (a.date || "9999").localeCompare(b.date || "9999"); }).map(function (event) { return eventCard(event, person); }).join("") || "<p class=\"review-empty\">登録された出来事はありません。</p>"; el.personCitationList.innerHTML = "<h3>人物情報の出典</h3>" + citationRows("person", person.id); el.personTimelineDialog.showModal(); }
  function injectPersonTools() { const detail = el.detailContent; if (!detail || !detail.querySelector(".detail-inner") || detail.querySelector(".v4-person-tools")) return; const person = state.data && state.data.persons.find(function (item) { return item.id === detail.dataset.personId; }); if (!person) return; state.selectedPersonId = person.id; const tools = document.createElement("div"); tools.className = "detail-actions v4-person-tools"; tools.innerHTML = "<button class=\"primary-button\" type=\"button\" data-person-timeline=\"" + person.id + "\">年表・出典</button><button class=\"secondary-button\" type=\"button\" data-person-transfer=\"" + person.id + "\">別の家系図へ</button>"; detail.querySelector(".detail-actions").after(tools); const fieldMap = { "生年月日": "birthDate", "没年月日": "deathDate", "出身地": "birthplace", "別名など": "name" }; detail.querySelectorAll(".detail-list > div").forEach(function (row) { const field = fieldMap[row.querySelector("dt")?.textContent.trim()]; if (!field) return; const count = state.data.citations.filter(function (citation) { return citation.targetType === "person" && citation.targetId === person.id && citation.fieldName === field; }).length; const button = document.createElement("button"); button.type = "button"; button.className = "field-citation-button"; button.dataset.citePerson = person.id; button.dataset.citeField = field; button.textContent = "▤" + (count ? " " + count : "＋"); button.setAttribute("aria-label", "この項目へ資料を引用"); row.querySelector("dd").appendChild(button); }); }
  async function openTransfer(personId) { const person = personById(personId); if (!person) return; const targets = state.data.trees.filter(function (tree) { return tree.id !== state.data.currentTree.id && !tree.isArchived; }); if (!targets.length) { showMessage("先に別の家系図を作成してください。", true); return; } el.transferForm.reset(); el.transferPersonId.value = person.id; el.transferPersonLabel.textContent = fullName(person); el.transferTargetTree.innerHTML = targets.map(function (tree) { return "<option value=\"" + tree.id + "\">" + escapeHtml(tree.name) + "</option>"; }).join(""); el.transferError.hidden = true; el.transferDialog.showModal(); }
  async function transfer(event) { event.preventDefault(); el.transferError.hidden = true; try { if (el.transferMode.value === "move" && !confirm("人物を現在の家系図から移動します。対象外の関係は引き継がれません。続けますか？")) return; const result = await DB.transferPerson(el.transferPersonId.value, el.transferTargetTree.value, { mode: el.transferMode.value, includeRelated: el.transferRelated.checked }); el.transferDialog.close(); await refresh(); showMessage(result.copiedCount + "人を" + (result.mode === "move" ? "移動" : "コピー") + "しました。対象外の関係 " + result.skippedRelationships + "件。"); if (result.mode === "move") location.reload(); } catch (error) { el.transferError.textContent = readable(error); el.transferError.hidden = false; } }

  async function renderSnapshots() { const items = await DB.listSnapshots(state.showAllSnapshots ? "all" : state.data.currentTree.id); el.snapshotList.innerHTML = items.map(function (snapshot) { const counts = snapshot.data || {}; return "<article class=\"snapshot-card\"><div><strong>" + escapeHtml(snapshot.title) + "</strong><p>" + escapeHtml(new Date(snapshot.createdAt).toLocaleString("ja-JP")) + "・" + escapeHtml(snapshot.reason || "手動作成") + "</p><small>人物 " + ((counts.persons || []).length) + "人／関係 " + ((counts.relationships || []).length) + "件／資料 " + ((counts.sources || []).length) + "件・約" + formatBytes(snapshot.approximateSize) + (snapshot.isManual ? "・手動" : "・自動") + "</small></div><div><button type=\"button\" data-snapshot-action=\"restore\" data-snapshot-id=\"" + snapshot.id + "\">復元</button><button class=\"danger-text\" type=\"button\" data-snapshot-action=\"delete\" data-snapshot-id=\"" + snapshot.id + "\">削除</button></div></article>"; }).join("") || "<p class=\"review-empty\">スナップショットはありません。</p>"; }
  async function openSnapshots() { closeSettings(); await refresh(); await renderSnapshots(); el.snapshotDialog.showModal(); }
  async function snapshotAction(event) { const button = event.target.closest("[data-snapshot-action]"); if (!button) return; if (button.dataset.snapshotAction === "restore") { if (!confirm("このスナップショットへ復元しますか？\n復元前の現在状態も自動保存します。添付ファイル本体はスナップショット対象外です。")) return; await DB.restoreSnapshot(button.dataset.snapshotId); location.reload(); } else if (confirm("このスナップショットを削除しますか？")) { await DB.deleteSnapshot(button.dataset.snapshotId); await renderSnapshots(); } }
  function showUndo(detail) { clearTimeout(state.undoTimer); el.undoMessage.textContent = (detail.label || "操作") + "を完了しました。"; el.undoBar.hidden = false; state.undoTimer = setTimeout(function () { el.undoBar.hidden = true; }, 10000); }

  async function renderStatistics() { if (!state.data || !el.statisticsGrid) return; const stats = await DB.getStatistics(); const cards = [["登録人物数", stats.persons + "人", "people"], ["存命／故人", stats.living + "人／" + stats.deceased + "人", "people"], ["世代数", stats.generations + "世代", "tree"], ["生年の範囲", (stats.oldestBirthYear || "—") + "〜" + (stats.newestBirthYear || "—"), "people"], ["関係数", stats.relationships + "件", "tree"], ["出典付き人物", stats.citedPersons + "人", "sources"], ["未確認情報", stats.unconfirmed + "件", "people"], ["写真登録率", stats.photoRate + "%", "people"], ["生年月日登録率", stats.birthRate + "%", "people"], ["未接続人物", stats.unconnected + "人", "people"], ["重複候補", stats.duplicateCandidates + "組", "people"], ["資料／出来事", stats.sources + "件／" + stats.events + "件", "sources"]]; el.statisticsGrid.innerHTML = cards.map(function (card) { return "<button type=\"button\" data-stat-view=\"" + card[2] + "\"><small>" + card[0] + "</small><strong>" + card[1] + "</strong><span>確認する →</span></button>"; }).join(""); }

  function download(blob, name) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); setTimeout(function () { URL.revokeObjectURL(url); }, 2000); }
  async function exportTreeJson() { closeSettings(); if (!confirm("この家系図のJSONには存命人物の個人情報、写真、添付ファイルが含まれます。保管場所に注意して書き出しますか？")) return; const backup = await DB.createBackup({ treeId: state.data.currentTree.id }); download(new Blob([JSON.stringify(backup, null, 2)], { type: "application/json;charset=utf-8" }), "家系図ノート_" + state.data.currentTree.name.replace(/[\\/:*?\"<>|]/g, "_") + "_" + new Date().toISOString().slice(0, 10) + ".json"); showMessage("家系図単体バックアップを書き出しました。"); }
  async function openGedcom() { closeSettings(); await refresh(); el.gedcomExportSummary.textContent = "「" + state.data.currentTree.name + "」の人物 " + state.data.persons.length + "人、関係 " + state.data.relationships.length + "件を書き出します。"; state.parsedGedcom = null; el.gedcomPreview.innerHTML = ""; el.importGedcomButton.disabled = true; el.gedcomError.hidden = true; el.gedcomDialog.showModal(); }
  async function exportGedcom() { if (!confirm("GEDCOMには存命人物の個人情報が含まれる可能性があります。SNSや公開サイトへ直接アップロードせず、安全な場所へ保存してください。")) return; const data = await DB.readTreeData(state.data.currentTree.id, false); const result = Gedcom.exportGedcom(data); download(new Blob(["\uFEFF" + result.text], { type: "text/plain;charset=utf-8" }), result.fileName); showMessage("UTF-8 GEDCOMを書き出しました。"); }
  async function parseGedcomFile() { const file = el.gedcomInput.files && el.gedcomInput.files[0]; el.gedcomInput.value = ""; if (!file) return; el.gedcomError.hidden = true; try { if (file.size > 20 * 1024 * 1024) throw new Error("GEDCOMファイルは20MB以下を選んでください。"); const parsed = Gedcom.parseGedcom(await file.text(), file.name); state.parsedGedcom = parsed; el.gedcomPreview.innerHTML = "<h3>解析結果</h3><dl><div><dt>家系図名</dt><dd>" + escapeHtml(parsed.treeName) + "</dd></div><div><dt>人物</dt><dd>" + parsed.persons.length + "人</dd></div><div><dt>家族・関係</dt><dd>" + parsed.familyCount + "家族／" + parsed.relationships.length + "件</dd></div><div><dt>出来事</dt><dd>" + parsed.eventCount + "件</dd></div><div><dt>警告</dt><dd>" + parsed.warningCount + "件</dd></div><div><dt>未対応タグ</dt><dd>" + parsed.unsupportedTagCount + "件</dd></div><div><dt>文字コード表記</dt><dd>" + escapeHtml(parsed.charset) + "</dd></div></dl>" + (parsed.warnings.length ? "<details><summary>警告一覧</summary><ul>" + parsed.warnings.slice(0, 100).map(function (warning) { return "<li>" + escapeHtml(warning) + "</li>"; }).join("") + "</ul></details>" : ""); el.importGedcomButton.disabled = false; } catch (error) { state.parsedGedcom = null; el.gedcomError.textContent = readable(error); el.gedcomError.hidden = false; el.importGedcomButton.disabled = true; } }
  async function importGedcom() { if (!state.parsedGedcom || !confirm("解析したGEDCOMを新しい家系図として取り込みますか？既存の家系図は上書きしません。")) return; setBusy(el.importGedcomButton, true, "取込中…"); try { await DB.importGedcomData(state.parsedGedcom, state.parsedGedcom.treeName); location.reload(); } catch (error) { el.gedcomError.textContent = readable(error); el.gedcomError.hidden = false; setBusy(el.importGedcomButton, false); } }

  function bind() {
    document.querySelectorAll("[data-v4-view]").forEach(function (button) { button.addEventListener("click", function () { switchView(button.dataset.v4View); }); });
    document.querySelectorAll("[data-app-view]").forEach(function (button) { button.addEventListener("click", function () { switchView(button.dataset.appView); }); });
    el.treeSwitcherButton.addEventListener("click", async function () { await refresh(); el.treeManagerDialog.showModal(); }); el.openTreeManagerButton.addEventListener("click", async function () { closeSettings(); await refresh(); el.treeManagerDialog.showModal(); });
    el.newTreeButton.addEventListener("click", function () { openTreeForm(null); }); el.treeForm.addEventListener("submit", saveTree); el.treeManagerList.addEventListener("click", treeAction); el.showArchivedTrees.addEventListener("change", renderTreeManager);
    el.openTimelineButton.addEventListener("click", function () { closeSettings(); switchView("timeline"); }); el.openSourcesButton.addEventListener("click", function () { closeSettings(); switchView("sources"); }); el.openStatisticsButton.addEventListener("click", function () { closeSettings(); switchView("statistics"); });
    el.addEventButton.addEventListener("click", function () { openEvent(null); }); el.eventForm.addEventListener("submit", saveEvent); el.timelineList.addEventListener("click", eventAction); [el.timelinePersonFilter, el.timelineTypeFilter, el.timelineVerificationFilter, el.timelineCitedOnly].forEach(function (control) { control.addEventListener("change", renderTimeline); }); el.timelineDecadeFilter.addEventListener("input", debounce(renderTimeline));
    el.addSourceButton.addEventListener("click", function () { openSource(null); }); el.sourceForm.addEventListener("submit", saveSource); el.sourceList.addEventListener("click", sourceAction); [el.sourceTypeFilter, el.sourceReliabilityFilter, el.sourceSort].forEach(function (control) { control.addEventListener("change", renderSources); }); el.sourceSearch.addEventListener("input", debounce(renderSources));
    el.attachmentInput.addEventListener("change", function () { const files = Array.from(el.attachmentInput.files || []); el.attachmentInput.value = ""; files.forEach(function (file) { if (file.size > DB.MAX_ATTACHMENT_BYTES) showMessage(file.name + "は20MBを超えるため追加できません。", true); else if (!["image/jpeg", "image/png", "image/webp", "application/pdf"].includes(file.type)) showMessage(file.name + "は対応形式ではありません。", true); else state.pendingAttachments.push({ file: file }); }); renderPendingAttachments(); }); el.pendingAttachmentList.addEventListener("click", function (event) { const button = event.target.closest("[data-remove-pending]"); if (button) { state.pendingAttachments.splice(Number(button.dataset.removePending), 1); renderPendingAttachments(); } }); el.storedAttachmentList.addEventListener("click", attachmentAction);
    el.citationForm.addEventListener("submit", saveCitation); el.citationExistingList.addEventListener("click", async function (event) { const button = event.target.closest("[data-delete-citation]"); if (button && confirm("引用を解除しますか？資料そのものは削除しません。")) { await DB.deleteCitation(button.dataset.deleteCitation); await refresh(); el.citationExistingList.innerHTML = citationRows(el.citationTargetType.value, el.citationTargetId.value); } }); el.personTimelineList.addEventListener("click", eventAction); el.personCitationList.addEventListener("click", async function (event) { const button = event.target.closest("[data-delete-citation]"); if (button && confirm("引用を解除しますか？資料そのものは削除しません。")) { await DB.deleteCitation(button.dataset.deleteCitation); await openPersonTimeline(state.selectedPersonId); } }); el.addPersonEventButton.addEventListener("click", function () { el.personTimelineDialog.close(); openEvent(null, state.selectedPersonId); }); el.citePersonButton.addEventListener("click", function () { openCitation("person", state.selectedPersonId, "other"); }); el.transferPersonButton.addEventListener("click", function () { openTransfer(state.selectedPersonId); }); el.transferForm.addEventListener("submit", transfer);
    el.detailContent.addEventListener("click", function (event) { const timeline = event.target.closest("[data-person-timeline]"); const transferButton = event.target.closest("[data-person-transfer]"); const cite = event.target.closest("[data-cite-person]"); if (timeline) openPersonTimeline(timeline.dataset.personTimeline); else if (transferButton) openTransfer(transferButton.dataset.personTransfer); else if (cite) openCitation("person", cite.dataset.citePerson, cite.dataset.citeField); }); document.addEventListener("click", function (event) { const menu = event.target.closest("[data-relationship-menu]"); if (menu) state.selectedRelationshipId = menu.dataset.relationshipMenu; }, true);
    const relationshipBody = el.relationshipMenuDialog.querySelector(".action-menu-body"); const citationButton = document.createElement("button"); citationButton.type = "button"; citationButton.textContent = "この関係へ資料を引用"; citationButton.addEventListener("click", function () { el.relationshipMenuDialog.close(); openCitation("relationship", state.selectedRelationshipId, "partnerRelationship"); }); relationshipBody.insertBefore(citationButton, relationshipBody.querySelector(".danger-menu-item"));
    const observer = new MutationObserver(function () { injectPersonTools(); }); observer.observe(el.detailContent, { childList: true, subtree: true });
    el.openSnapshotsButton.addEventListener("click", openSnapshots); el.createSnapshotButton.addEventListener("click", async function () { await DB.createSnapshot({ title: "手動スナップショット", reason: "利用者が手動作成", manual: true }); await renderSnapshots(); showMessage("手動スナップショットを作成しました。"); }); el.showAllSnapshotsButton.addEventListener("click", async function () { state.showAllSnapshots = !state.showAllSnapshots; el.showAllSnapshotsButton.textContent = state.showAllSnapshots ? "現在の家系図だけ表示" : "削除済み家系図の履歴も表示"; await renderSnapshots(); }); el.snapshotList.addEventListener("click", snapshotAction);
    globalThis.addEventListener("family-tree-undo", function (event) { showUndo(event.detail || {}); }); el.undoButton.addEventListener("click", async function () { setBusy(el.undoButton, true, "復元中…"); try { await DB.undoLast(); location.reload(); } catch (error) { setBusy(el.undoButton, false); showMessage(readable(error), true); } }); el.dismissUndoButton.addEventListener("click", function () { el.undoBar.hidden = true; });
    el.exportTreeJsonButton.addEventListener("click", exportTreeJson); el.openGedcomButton.addEventListener("click", openGedcom); el.exportGedcomButton.addEventListener("click", exportGedcom); el.gedcomInput.addEventListener("change", parseGedcomFile); el.importGedcomButton.addEventListener("click", importGedcom);
    el.statisticsGrid.addEventListener("click", function (event) { const button = event.target.closest("[data-stat-view]"); if (button) switchView(button.dataset.statView); });
  }

  async function boot() {
    try { cache(); if (!DB || DB.DB_VERSION !== 4 || !Gedcom) throw new Error("試作4のプログラムを読み込めませんでした。"); renderSourceFilters(); bind(); await DB.initialize(); await refresh(); }
    catch (error) { showMessage(readable(error, "試作4の機能を起動できませんでした。"), true); }
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot, { once: true }); else boot();
}());
